import type { Project, Role, User } from '../shared/types';

export const BUSINESS_CASES: Project[] = [
  {
    id: 'p-pre',
    code: 'PROJ-2026-001',
    name: '客房一次性用品采购项目',
    type: '货物',
    method: '公开招标',
    stage: 'BIDDING',
    organization: '集团采购中心',
    agent: '张经办',
    budget: 1500000,
    bidDeadline: '2026-07-10T14:00:00Z',
    riskLevel: 'LOW',
    archiveCompleteness: 45,
    isExternal: false,
  },
  {
    id: 'p-award',
    code: 'PROJ-2026-002',
    name: '客房布草集中采购项目',
    type: '货物',
    method: '邀请招标',
    stage: 'AWARD',
    organization: '集团采购中心',
    agent: '李经办',
    budget: 3200000,
    riskLevel: 'MEDIUM',
    archiveCompleteness: 85,
    isExternal: false,
  },
  {
    id: 'p-food',
    code: 'PROJ-2026-003',
    name: '上海滨江酒店食材供应商比选',
    type: '货物',
    method: '竞争性比选',
    stage: 'FULFILLMENT',
    organization: '上海滨江酒店',
    agent: '王采购',
    budget: 800000,
    riskLevel: 'HIGH',
    archiveCompleteness: 70,
    isExternal: false,
  },
  {
    id: 'p-ext',
    code: 'PROJ-2026-004',
    name: '客房改造工程外部交易备案项目',
    type: '工程',
    method: '依法必须招标',
    stage: 'EXTERNAL_FILED',
    organization: '华东区域公司',
    agent: '赵工程',
    budget: 12500000,
    riskLevel: 'LOW',
    archiveCompleteness: 100,
    isExternal: true,
    externalDetails: {
      platformName: '上海市建设工程交易中心',
      projectCode: 'SH-GC-2026-10293',
    },
  },
];

export const DEMO_USERS: Record<Role, User> = {
  GROUP_PROCUREMENT_MANAGER: { id: 'u1', name: '王总监', role: 'GROUP_PROCUREMENT_MANAGER', organization: '集团采购中心' },
  PROCUREMENT_AGENT: { id: 'u2', name: '张经办', role: 'PROCUREMENT_AGENT', organization: '集团采购中心' },
  HOTEL_PROCUREMENT: { id: 'u3', name: '李采购', role: 'HOTEL_PROCUREMENT', organization: '北京中心酒店' },
  HOTEL_FINANCE: { id: 'u4', name: '赵财务', role: 'HOTEL_FINANCE', organization: '北京中心酒店' },
  PLATFORM_OPERATIONS: { id: 'u5', name: '陈运营', role: 'PLATFORM_OPERATIONS', organization: '集团数字运营部' },
  SUPPLIER: { id: 'u6', name: '企业代表', role: 'SUPPLIER', organization: '江苏优选酒店用品有限公司' },
  SUPPLIER_ADMIN: { id: 'u7', name: '管理员代表', role: 'SUPPLIER_ADMIN', organization: '江苏优选酒店用品有限公司' },
  SUPPLIER_BIDDER: { id: 'u8', name: '报价专员', role: 'SUPPLIER_BIDDER', organization: '江苏优选酒店用品有限公司' },
  EXPERT: { id: 'u9', name: '刘专家', role: 'EXPERT', organization: '外部专家库' },
  FINANCE_REVIEWER: { id: 'u10', name: '周审核', role: 'FINANCE_REVIEWER', organization: '集团财务共享中心' },
  DISCIPLINARY_AUDIT: { id: 'u11', name: '孙纪检', role: 'DISCIPLINARY_AUDIT', organization: '集团纪委审计部' },
  SYSTEM_ADMIN: { id: 'u12', name: '系统管理员', role: 'SYSTEM_ADMIN', organization: '集团信息部' },
};
