import { statusLabelMap } from "../../utils/status-labels";

export const INTERNAL_STATUS_ORDER = [
  "project_created",
  "document_preparing",
  "document_published",
  "registration_open",
  "bidding_open",
  "bidding_locked",
  "expert_reviewing",
  "review_report_frozen",
  "award_approving",
  "awarded_pending_order",
  "result_notified",
  "contract_registered",
  "performing",
  "evaluated",
  "archived",
  "closed"
];

export const EXTERNAL_STATUS_ORDER = [
  "external_project_recorded",
  "external_announcement_uploaded",
  "external_result_uploaded",
  "external_result_recorded",
  "external_contract_registered",
  "external_performing",
  "external_evaluated",
  "external_archived",
  "external_closed"
];

export const WORKBENCH_STATUS_TEXT: Record<string, string> = {
  ...statusLabelMap,
  awarded_pending_order: "待生成订单",
  pending_confirmation: "待供应商确认",
  supplier_confirmed: "供应商已确认",
  performing: "履约中",
  partially_received: "部分收货",
  received: "已收货",
  exception: "异常处理中",
  closed: "已关闭",
  pending_verification: "待核验",
  verified: "已通过",
  rejected: "已驳回",
  submitted_locked: "已锁定",
  superseded: "已更正",
  complete: "完整",
  incomplete: "缺项",
  collecting: "归集中",
  sealed: "已封存",
  supplemented: "已补档",
  supplement_requested: "待补档审批",
  supplement_approved: "补档已批准",
  supplement_rejected: "补档已驳回",
  invoice: "发票",
  delivery_note: "送货单",
  acceptance_record: "验收单",
  other: "其他资料",
  partial: "部分收货",
  full: "全部收货",
  quantity_mismatch: "数量不符",
  quality_issue: "质量问题",
  delivery_delay: "延期交付",
  missing_documents: "资料缺失",
  pending_resolution: "待处理",
  none: "无",
  cooperation: "配合度",
  priceReasonableness: "价格合理性",
  quality: "质量",
  delivery: "交付",
  service: "服务"
};
