export const statusLabelMap: Record<string, string> = {
  "内部公开招采": "内部公开招采",
  "询价 / 比选": "询价 / 比选",
  active: "启用",
  admitted: "已准入",
  archived: "已归档",
  assigned: "已分配",
  accepted: "已验收",
  accepted_with_exception: "异常验收",
  adapter_contract_ready: "合同摘要已生成",
  approved: "已批准",
  avoidance_pending: "待回避确认",
  awarded_pending_order: "待生成订单",
  award_approving: "定标审批中",
  bid_response_file: "响应文件",
  bidding_locked: "报价已锁定",
  bidding_open: "报价中",
  cancelled: "已取消",
  checking: "检查中",
  closed: "已关闭",
  collecting: "归集中",
  complete: "完整",
  completed: "已完成",
  contract_registered: "合同已登记",
  created: "已创建",
  draft: "草稿",
  denied: "已拒绝",
  document_preparing: "采购文件编制中",
  document_published: "采购文件已发布",
  enabled: "启用",
  evaluated: "已评价",
  exception: "异常",
  expired: "已过期",
  external_announcement_uploaded: "外部公告材料已上传",
  external_archived: "外部档案已归档",
  external_closed: "外部项目已关闭",
  external_contract_registered: "外部合同已登记",
  external_draft: "外部交易草稿",
  external_evaluated: "外部评价完成",
  external_performing: "外部履约中",
  external_project_recorded: "外部项目已登记",
  external_result_recorded: "外部结果已备案",
  external_result_uploaded: "外部结果材料已上传",
  inactive: "停用",
  incomplete: "不完整",
  in_review: "审批中",
  initial_review_passed: "初审通过",
  initial_review_rejected: "初审驳回",
  invalid: "无效",
  locked: "已锁定",
  matched: "已核对",
  method_decided: "已定采购方式",
  mismatched: "金额不一致",
  partial: "部分收货",
  partially_received: "部分收货",
  passed: "通过",
  pending: "待处理",
  pending_initial_review: "待初审",
  pending_payment: "待付款",
  pending_confirmation: "待供应商确认",
  pending_review: "待审核",
  pending_resolution: "待处理",
  pending_verification: "待核验",
  performing: "履约中",
  permitted: "已允许",
  planned: "已计划",
  project_created: "已发起项目",
  published: "已发布",
  qualified: "资格通过",
  received: "已收货",
  recorded: "已记录",
  registered: "已登记",
  rejected: "已驳回",
  rejected_tax: "税额异常",
  request_submitted: "采购申请已提交",
  restricted: "受限",
  result_notified: "结果已通知",
  reviewing: "审核中",
  revoked: "已撤销",
  sealed: "已封存",
  sent: "已发送",
  special_vat: "增值税专票",
  submitted: "已提交",
  submitted_locked: "已提交并锁定",
  supplement_approved: "补档已批准",
  supplement_rejected: "补档已驳回",
  supplement_requested: "待补档审批",
  supplemented: "已补档",
  supplier_confirmed: "供应商已确认",
  superseded: "已更正",
  suspended: "已暂停",
  verified: "已通过",
  viewed: "已查看",
  voided: "已作废",
  withdrawn: "已撤回",
  resubmitted: "已重新提交",

  acceptance_record: "验收单",
  cooperation: "配合度",
  delivery: "交付",
  delivery_delay: "延期交付",
  delivery_note: "送货单",
  delisted: "已下架",
  invoice: "发票",
  listed: "已上架",
  mall_order: "商城订单",
  mall_product_image: "商品图片",
  mall_settlement_invoice: "商城结算发票",
  missing_documents: "资料缺失",
  none: "无",
  other: "其他",
  priceReasonableness: "价格合理性",
  quality: "质量",
  quality_issue: "质量问题",
  quantity_mismatch: "数量不符",
  service: "服务",

  comparison: "询价/比价",
  internal_open: "内部公开",
  invited_suppliers: "定向邀请",
  public_internal: "内部公开",
  selection: "比选",
  sample_room: "样板间",
  opening_package: "开业包",
  bulk_purchase_package: "批量采购包",
  shipped: "已发货",
  payable: "待付款",
  payment_requested: "付款申请中",
  payment_reserved: "已占用",
  payment_capture: "付款确认",
  payment_reserve: "付款占用",
  reserved: "已占用",
  released: "已释放",
  reversed: "已冲正",
  simulated: "已登记",
  frozen: "已冻结",
  return_requested: "已申请退货",
  return_approved: "退货已同意",
  return_rejected: "退货已驳回",
  processed: "已处理"
};

export const auditActionLabelMap: Record<string, string> = {
  "announcement.create": "创建公告",
  "announcement.publish": "发布公告",
  "archive.check": "档案完整性检查",
  "archive.seal": "封存档案",
  "archive.snapshot": "生成档案快照",
  "archive_item.update": "更新档案项",
  "archive_supplement.apply": "提交补档材料",
  "archive_supplement_request.approve": "批准补档申请",
  "archive_supplement_request.reject": "驳回补档申请",
  "archive_supplement_request.submit": "发起补档申请",
  "auth.login": "登录系统",
  "auth.login.denied": "登录失败",
  "auth.login.local_disabled": "账号登录方式受限",
  "auth.logout": "退出登录",
  "auth.mock_login": "账号登录",
  "auth.mock_role_switch": "账号身份切换",
  "audit_log.read.denied": "读取审计日志被拒绝",
  "award_approval.bid.denied": "定标供应商校验未通过",
  "award_approval.create": "创建定标审批",
  "award_approval.create.denied": "创建定标审批被拒绝",
  "award_approval.deadline.denied": "定标时点校验未通过",
  "award_approval.mock_approve": "审批定标结果",
  "award_approval.reason.denied": "定标理由校验未通过",
  "award_approval.read.denied": "读取定标审批被拒绝",
  "award_approval.review_report.denied": "评审报告未满足定标条件",
  "award_approval.status.denied": "定标状态校验未通过",
  "award_approval.submit": "提交定标审批",
  "award_approval.supplier.denied": "定标供应商无效",
  "award_approval.supplier_restricted.denied": "受限供应商不可定标",
  "bid.create.denied": "提交报价被拒绝",
  "file.discard": "作废文件",
  "file.download": "下载文件",
  "file.replace": "替换文件",
  "file.upload": "上传文件",
  "mall_cart.update": "更新购物车",
  "mall_cart.clear": "清空采购清单",
  "mall_fund.recharge": "登记资金充值",
  "mall_fund.recharge.denied": "登记资金充值被拒绝",
  "mall_fund.read.denied": "读取资金账户被拒绝",
  "mall_invoice.upload": "上传商城发票",
  "mall_invoice.verify": "核验商城发票",
  "mall_invoice.verify.denied": "核验商城发票被拒绝",
  "mall_invoice.verify.reject_tax": "发票税额校验驳回",
  "mall_order.confirm": "供应商确认商城订单",
  "mall_order.copy": "复制商城订单",
  "mall_order.receive": "商城订单收货",
  "mall_order.submit": "提交商城订单",
  "mall_product.create": "创建商品",
  "mall_product.status.update": "更新商品状态",
  "mall_product.update": "编辑商品",
  "mall_questionnaire.publish": "发布采购问卷",
  "mall_return.review": "处理退货申请",
  "mall_return.submit": "提交退货申请",
  "mall_scenario_template.create": "创建快捷采购包",
  "mall_shipment.create": "登记发货",
  "mall_payment.ledger.denied": "付款台账维护被拒绝",
  "performance_node.create": "创建履约节点",
  "performance_node.update": "更新履约节点",
  "project.create-from-request": "由采购申请发起项目",
  "project.transition": "更新项目状态",
  "procurement-document.create": "创建采购文件",
  "procurement-document.publish-lock": "发布采购文件",
  "procurement-document.revision.create": "创建采购文件修订版",
  "procurement-document.submit-review": "提交采购文件审核",
  "procurement-document.update": "更新采购文件",
  "procurement-document.void": "作废采购文件",
  "procurement-request.approve": "审批通过采购申请",
  "procurement-request.cancel": "取消采购申请",
  "procurement-request.create": "创建采购申请",
  "procurement-request.delete": "删除草稿采购申请",
  "procurement-request.method-decision": "判定采购方式",
  "procurement-request.reject": "驳回采购申请",
  "procurement-request.submit": "提交采购申请",
  "purchase_order.generate": "生成采购订单",
  "purchase_order.change": "变更采购订单",
  "purchase_order.close": "关闭采购订单",
  "purchase_order.confirm": "供应商确认订单",
  "receipt.handle": "处理收货异常",
  "receipt.record": "登记收货验收",
  "registration.qualify": "审核报名资格",
  "registration.submit": "提交报名资料",
  "scoring_sheet.save": "保存评分表",
  "settlement_bill.approve": "审核通过结算单",
  "settlement_bill.generate": "生成结算单",
  "settlement_bill.reject": "驳回结算单",
  "settlement_bill.submit": "提交结算单",
  "settlement_material.reject": "驳回结算资料",
  "settlement_material.upload": "上传结算资料",
  "settlement_material.verify": "核验结算资料",
  "supplier-invitation.send": "发送供应商邀请",
  "supplier.admission.create": "新增供应商准入",
  "supplier.category-authorize": "维护供应商品类授权",
  "supplier.profile.update": "更新供应商资料",
  "supplier.register.local_mock": "供应商注册",
  "supplier.restrict": "限制供应商",
  "supplier.review.record": "记录供应商评审",
  "supplier.seal-sample.record": "上传封样资料",
  "supplier.status.update": "更新供应商状态",
  "supplier_evaluation.submit_locked": "提交供应商评价"
};

export const objectTypeLabelMap: Record<string, string> = {
  announcement: "公告",
  archive_item: "档案项",
  archive_supplement_request: "补档申请",
  audit_log: "审计日志",
  auth_account: "认证账号",
  auth_provider: "认证提供方",
  acceptance_payment: "验收付款记录",
  award_approval: "定标审批",
  bid: "报价单",
  bid_lock: "报价锁定",
  contract_ledger: "合同台账",
  fund_ledger: "付款流水",
  invoice: "发票",
  mall_invoice: "商城发票",
  mall_order: "商城订单",
  mall_product: "商城商品",
  mall_cart: "采购清单",
  mall_fund_account: "资金账户",
  mall_questionnaire: "采购问卷",
  mall_return: "退货申请",
  mall_scenario_template: "快捷采购包",
  performance_node: "履约节点",
  procurement_document: "采购文件",
  procurement_request: "采购申请",
  project: "采购项目",
  purchase_order: "采购订单",
  receipt_record: "收货记录",
  registration: "报名资料",
  scoring_sheet: "评分表",
  settlement_bill: "结算单",
  settlement_finance: "结算财务",
  settlement_material: "结算资料",
  supplier: "供应商",
  supplier_invitation: "供应商邀请",
  supplier_evaluation: "供应商评价",
  user: "用户"
};

export const auditReasonLabelMap: Record<string, string> = {
  AUDIT_LOG_READ_DENIED: "无审计日志读取权限",
  "deadline not reached": "报价截止前不可执行",
  "invalid credentials": "账号或密码错误",
  "local password login disabled": "账号登录方式受限",
  "local/test mock only": "账号入口记录"
};

export function labelStatus(value: string | undefined | null) {
  if (!value) return "-";
  return statusLabelMap[value] ?? "待确认";
}

export function labelAuditAction(value: string | undefined | null) {
  if (!value) return "-";
  return auditActionLabelMap[value] ?? "业务操作记录";
}

export function labelObjectType(value: string | undefined | null) {
  if (!value) return "-";
  return objectTypeLabelMap[value] ?? "业务对象";
}

export function labelAuditReason(value: string | undefined | null) {
  if (!value) return "-";
  return auditReasonLabelMap[value] ?? "规则校验记录";
}

export function formatDateTime(value: string | undefined | null) {
  return value ? value.replace("T", " ").slice(0, 16) : "-";
}

export function isImageFile(fileName?: string, contentType?: string) {
  if (contentType?.toLowerCase().startsWith("image/")) return true;
  return /\.(png|jpe?g|webp|gif|bmp)$/i.test(fileName ?? "");
}
